- name: remove /var/www/bahmni_config
  file: path=/var/www/bahmni_config state=absent

- name: Copy implementation config to /var/www/bahmni_config
  synchronize:
    src: /etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}_config/
    dest: /var/www/bahmni_config
    rsync_path: "sudo rsync"
    compress: true
    delete: yes
    recursive: true
    rsync_opts:
      - "--exclude=.git"

- name: Ensure directory and permissions for /var/www/bahmni_config
  file: path=/var/www/bahmni_config state=directory owner={{ bahmni_user }} group={{ bahmni_group }} mode=755 recurse=yes

- name: check if obscalculator exists
  stat: path=/var/www/bahmni_config/openmrs/obscalculator
  register: obscalculator_dir

- name: Link obscalculator in openmrs application data directory
  file: src=/var/www/bahmni_config/openmrs/obscalculator  dest=/opt/openmrs/obscalculator state=link owner={{ bahmni_user }} group={{ bahmni_group }}
  when: obscalculator_dir.stat.exists == True

- name: check if ordertemplates exists
  stat: path=/var/www/bahmni_config/openmrs/ordertemplates
  register: ordertemplates_dir

- name: Link order templates in openmrs application data directory if it exists
  file: src=/var/www/bahmni_config/openmrs/ordertemplates  dest=/opt/openmrs/ordertemplates state=link owner={{ bahmni_user }} group={{ bahmni_group }}
  when: ordertemplates_dir.stat.exists == True

- name: check if encounterModifier exists
  stat: path=/var/www/bahmni_config/openmrs/encounterModifier
  register: encounterModifier_dir

- name: Link encounter modifiers in openmrs application data directory if it exists
  file: src=/var/www/bahmni_config/openmrs/encounterModifier  dest=/opt/openmrs/encounterModifier state=link owner={{ bahmni_user}} group={{ bahmni_group }}
  when: encounterModifier_dir.stat.exists == True

- name: check if patientMatchingAlgorithm exists
  stat: path=/var/www/bahmni_config/openmrs/patientMatchingAlgorithm
  register: patientMatchingAlgorithm_dir

- name: Link patient match algorithms in openmrs application data directory if it exists
  file: src=/var/www/bahmni_config/openmrs/patientMatchingAlgorithm  dest=/opt/openmrs/patientMatchingAlgorithm state=link owner={{ bahmni_user }} group={{ bahmni_group }}
  when: patientMatchingAlgorithm_dir.stat.exists == True

- name: check if elisFeedInterceptor exists
  stat: path=/var/www/bahmni_config/openmrs/elisFeedInterceptor
  register: elisFeedInterceptor_dir

- name: Link elis feed interceptors in openmrs application data directory if it exists
  file: src=/var/www/bahmni_config/openmrs/elisFeedInterceptor  dest=/opt/openmrs/elisFeedInterceptor state=link owner={{ bahmni_user }} group={{ bahmni_group }}
  when: elisFeedInterceptor_dir.stat.exists == True

- name: check if observationsAdder exists
  stat: path=/var/www/bahmni_config/openmrs/observationsAdder
  register: observationsAdder_dir

- name: Link observation adders in openmrs application data directory if it exists
  file: src=/var/www/bahmni_config/openmrs/observationsAdder  dest=/opt/openmrs/observationsAdder state=link owner={{ bahmni_user }} group={{ bahmni_group }}
  when: observationsAdder_dir.stat.exists == True

#TODO: Below 3 tasks to be removed after removing its dependencies from bahmni-core
- name: remove /opt/openmrs/bahmni_config
  file: path=/opt/openmrs/bahmni_config state=absent

- name: Link entire bahmni_config in openmrs application data directory
  file: src=/var/www/bahmni_config dest=/opt/openmrs/bahmni_config state=link owner={{ bahmni_user }} group={{ bahmni_group }}

- name: Run openmrs liquibase migrations
  script: run-implementation-openmrs-liquibase.sh
  when: passive is not defined or passive != 'yes'

