- name: Stop Openerp
  service:
    name=openerp
    state=stopped
  when: passive is not defined or passive != 'yes'

- name: Removing files regarding Custom ERP modules
  file:
      path=/usr/lib/python2.6/site-packages/openerp-7.0_20130301_002301-py2.6.egg/openerp/addons/{{item}}
      state=absent
  with_items:
      - "{{ modules }}"

- name: Removing files regarding bahmni ERP modules
  file:
      path=/usr/lib/python2.6/site-packages/openerp-7.0_20130301_002301-py2.6.egg/openerp/addons/{{item}}
      state=absent
  with_items:
      - "{{ modules_erp }}"
  
- name: Download Custom ERP modules from Git
  get_url:
    url={{ erp_custom_modules_url }}
    force=yes
    dest=/opt/bahmni-erp/possible-erp-custom-master.zip

- name: Download possible bahmni ERP modules from url
  get_url:
    url={{ erp_modules_url }}
    force=yes
    dest=/opt/bahmni-erp/possible-erp-master.zip

- name: Unzip downloaded Custom ERP Module
  command: unzip -o /opt/bahmni-erp/possible-erp-custom-master.zip -d /opt/bahmni-erp/possible-erp-custom-master

- name: Unzip downloaded Custom ERP Module
  command: unzip -o /opt/bahmni-erp/possible-erp-master.zip -d /opt/bahmni-erp/possible-erp-master

- name: Moving Custom modules to Addons Folder
  command: mv -f /opt/bahmni-erp/possible-erp-custom-master/possible-erp-custom-master/{{item}} /usr/lib/python2.6/site-packages/openerp-7.0_20130301_002301-py2.6.egg/openerp/addons/
  with_items: "{{ modules }}"

- name: Moving possible erp modules to Addons Folder
  command: mv -f /opt/bahmni-erp/possible-erp-master/openerp-modules/{{item}} /usr/lib/python2.6/site-packages/openerp-7.0_20130301_002301-py2.6.egg/openerp/addons/
  with_items: "{{ modules_erp }}"

- name: Removing temporary files from bahmni-erp
  file:
      path=/opt/bahmni-erp/{{item}}
      state=absent
  with_items:
      - "{{ bahmni_erp_temp_files }}"

- name: Start Openerp
  service:
    name=openerp
    state=started
  when: passive is not defined or passive != 'yes'
